version: '2.3'
services:
  redis:
    image: redis:5.0.3
    ports:
      - "6379:6379"

  service:
    image: arruda/pytorch-object-detection-service:master
    command: echo "ok"
    build:
      context: '.'
      dockerfile: 'Dockerfile'